# Bridge Race Module Settings

file_version: 1
menus:
  vote:
    item: BRICKS

items:
  starting_items:
    - "BRICKS:64:0"

effects:
  starting_effects: []
  respawn_effects:
    - "DAMAGE_RESISTANCE:60:2"
